// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateUserOperation OperationName = "CreateUser"
	DeleteUserOperation OperationName = "DeleteUser"
	GetUserOperation    OperationName = "GetUser"
	UpdateUserOperation OperationName = "UpdateUser"
)
